[package]
name = "executive"
version = "0.1.0"
authors = ["James W. Fawcett <jfawcett@twcny.rr.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
component_a = { path = "../component_a" }
component_b = { path = "../component_b" }
display = { path = "../../display" }